# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools
	
script: make test


r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5

after_success:
  - Rscript -e 'library(covr); codecov()'



