# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


before_install:
  - svn co https://projects.coin-or.org/svn/Clp/stable/1.16 coin-Clp
  - cd coin-Clp
  - make ./configure -C
  - make


r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5

after_success:
  - Rscript -e 'library(covr); codecov()'



