# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get install coinor-clp
  - sudo apt-get install coinor-libclp-dev

r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5
 - rte-antares-rpackage/antaresEditObject

after_success:
  - Rscript -e 'library(covr); codecov()'



