# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

#before_install:
# - git clone --branch=stable/2.9 https://github.com/coin-or/Cbc Cbc-2.9
# - cd Cbc-2.9
# - git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools/
# - ./configure
# - make
# - make install


	
before_install:
  - svn co http://www.coin-or.org/svn/CoinBinary/OptimizationSuite/stable/1.8
  - cd 1.8
  - ./get.AllThirdParty
  - mkdir build
  - cd build
  - ../configure --with-gmpl --enable-gnu-packages
  - make install




r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5

after_success:
  - Rscript -e 'library(covr); codecov()'



