# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r: bioc-devel

before_install: R --with-clp-include


r_github_packages:
 - hadley/devtools#1263
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5

after_success:
  - Rscript -e 'library(covr); codecov()'
